import { useState } from 'react'
import Head from 'next/head'
import Modal from '../components/UI/Modal'
import Banner from '../components/UI/Banner'
import Properties from '../components/Home/Properties'
import FilteredProperties from '../components/Home/FilteredProperties'

export default function Home({dataSale, dataRent}) {

	const [isModal, setIsModal] = useState(false)

	return (
    	<div>
			<Head>
				<title>Homepage | RSTATE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<Banner handleModal={() => setIsModal(true)}/>
			{isModal && <Modal>
				<FilteredProperties 
					classesInput="border border-gray-300 rounded"
					filteredModal
					handleClose={() => setIsModal(false)}/>
			</Modal>}
			<div className="px-5 py-10">
				<div className="container">
					<Properties data={dataSale.hits} title="For Sale"/>
					<Properties data={dataRent.hits} title="For Rent"/>
				</div>
			</div>
    	</div>
  	)
}



export const getServerSideProps = async() => {
	const [forSaleRes, forRentRes] = await Promise.all([
		fetch("https://bayut.p.rapidapi.com/properties/list?locationExternalIDs=5002%2C6020&purpose=for-sale&hitsPerPage=10&page=0&lang=en&sort=city-level-score&rentFrequency=monthly&categoryExternalID=4", {
			"method": "GET",
			"headers": {
                "x-rapidapi-host": "bayut.p.rapidapi.com",
                "x-rapidapi-key": "7bef28009dmshedc105df6814739p15d209jsn096ca5e8e8f0"
            }
		}), 
		fetch("https://bayut.p.rapidapi.com/properties/list?locationExternalIDs=5002%2C6020&purpose=for-rent&hitsPerPage=10&page=0&lang=en&sort=city-level-score&rentFrequency=monthly&categoryExternalID=4", {
			"method": "GET",
			"headers": {
                "x-rapidapi-host": "bayut.p.rapidapi.com",
                "x-rapidapi-key": "7bef28009dmshedc105df6814739p15d209jsn096ca5e8e8f0"
            }
		})
	  ]);
	  const [forSale, forRent] = await Promise.all([
		forSaleRes.json(), 
		forRentRes.json()
	  ]);

	return {
		props: {
			dataSale: forSale,
			dataRent: forRent
		}
	}
}