import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { IoIosCall } from 'react-icons/io'
import { MdVerified } from 'react-icons/md'
import Modal from '../../components/UI/Modal'
import { FaRegWindowClose } from 'react-icons/fa'
import { GoChevronLeft, GoChevronRight, GoMail } from 'react-icons/go'
import PropertyDescription from '../../components/Property/PropertyDescription'


const PropertyDetail = ({data}) => {

    const [isModal, setIsModal] = useState(null)

    const handleNext = () => {
        if(isModal === data.photos.slice(0, 10).length) {
            setIsModal(1)
        } else {
            setIsModal(isModal + 1)
        }
    }

    const handleBack = () => {
        if(isModal === 1) {
            setIsModal(data.photos.slice(0, 10).length)
        } else {
            setIsModal(isModal - 1)
        }
    }

    return (
        <div>
            <Head>
				<title>Property | RSTATE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <div className="px-5 py-10">
                <div className="container">

                    <div className="flex flex-col md:flex-row">
                        <div className="relative w-full h-[250px] md:min-h-[450px] md:w-[500px] lg:w-[700px]">
                            <Image src={data.coverPhoto.url} layout="fill" objectFit="cover"/> 
                        </div>

                        <div className="flex-1 flex flex-col items-center justify-center text-gray-900 bg-white py-5 px-4 mt-5 md:mt-0 md:ml-4 shadow-md rounded text-center">
                            <div className="relative w-20 h-20">
                                <Image 
                                    src={data?.agency?.logo?.url ? data.agency.logo.url : "/images/next.png"} 
                                    layout="fill" 
                                    objectFit="contain" 
                                    alt={data?.agency?.name ? data.agency.name : 'agency'}/>
                            </div>
                            <h1 className="font-medium text-xl lg:text-2xl">{data?.agency?.name ? data.agency.name : 'Agency Real Estate'}</h1>
                            <h1 className="mt-2 text-sm">
                                Contact Name: <br /> <span className="text-base font-medium">{data.contactName}</span></h1>
                            <h1 className="mt-2 text-sm">Phone Number: <br /> <span className="text-base font-medium">{data.phoneNumber.mobile}</span></h1>
                            {data.verification.status === 'verified' && (
                                <div className="flex items-center space-x-3 mt-3">
                                    <MdVerified className="text-xl text-green-600"/>
                                    <p className="text-sm">verified property</p>
                                </div>
                            )}
                            <div className="flex md:flex-col space-x-3 md:space-x-0 md:space-y-3 mt-5">
                                <a href="https://wa.me/6285848128298" 
                                    className="btn py-2 px-4 flex items-center text-sm lg:text-base">
                                    <IoIosCall className="text-lg mr-2"/>    
                                    Call Agency
                                </a>
                                
                                <a href="mailto:permanahendra2308@gmail.com" 
                                    className="btn bg-blue-500 py-2 px-4 flex items-center flex-1 text-sm lg:text-base">
                                    <GoMail className="text-lg mr-2"/>
                                    Send Email
                                </a>
                            </div>
                        </div>
                    </div>
                    
                    <PropertyDescription data={data} setIsModal={setIsModal}/>
                    {isModal && (
                        <Modal imgModal>
                            <div className="relative w-full h-full">
                                <Image src={data.photos[isModal - 1].url} alt={data.photos[isModal - 1].id} layout="fill" objectFit="cover"/>
                                <div className="absolute -top-10 right-0 bg-white p-2" onClick={() => setIsModal(null)}>
                                    <FaRegWindowClose className="text-2xl font-bold text-red-500 cursor-pointer"/>
                                </div>
                                <div className="absolute flex items-center justify-between w-full h-full text-white">
                                    <GoChevronLeft className="text-3xl -ml-7 cursor-pointer" onClick={handleBack}/>
                                    <GoChevronRight className="text-3xl -mr-7 cursor-pointer" onClick={handleNext}/>
                                </div>
                            </div>
                        </Modal>
                    )}
                </div>
            </div>
        </div>
    )
}


export const getServerSideProps = async({params}) => {
    const res = await fetch(`https://bayut.p.rapidapi.com/properties/detail?externalID=${params.propertyId}`, {
        "method": "GET",
        "headers": {
            "x-rapidapi-host": "bayut.p.rapidapi.com",
            "x-rapidapi-key": "7bef28009dmshedc105df6814739p15d209jsn096ca5e8e8f0"
        }
    })
    const data = await res.json()

    return {
        props: { data }
    }
}

export default PropertyDetail
